# Generated by Django 6.0.3 on 2026-05-01 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_uniformes", "0004_favoritos_cantidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallespedido",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="historialstock",
            name="producto",
        ),
        migrations.AddField(
            model_name="detallespedido",
            name="talla_variante",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_uniformes.tallavariante",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historialstock",
            name="talla_variante",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecommerce_uniformes.tallavariante",
            ),
            preserve_default=False,
        ),
    ]
