# Generated by Django 6.0.3 on 2026-05-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_uniformes", "0006_itemcarrito"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
            ],
        ),
    ]
